[theme]
base="dark"
primaryColor="#f63366"
backgroundColor="#121212"  # Dark gray, lighter than #0e1117
secondaryBackgroundColor="#333333"  # Medium gray, lighter than #262730
textColor="#ffffff"
font="sans serif"
