[theme]
base="dark"
primaryColor="#f63366"
backgroundColor="hsl(228, 15%, 40%)"  # Lighter gray
secondaryBackgroundColor="hsl(228, 15%, 35%)"  # Slightly darker gray than backgroundColor
textColor="#ffffff"
font="sans serif"
