[theme]
base="dark"
primaryColor="#f63366"
backgroundColor="#21232C"  # Original dark grey
secondaryBackgroundColor="#1A1B20"  # Slightly darker than the original
textColor="#ffffff"
font="sans serif"
